name: bold_beauty_lounge
description: "Application mobile pour Bold Beauty Lounge - Salon de beauté à Casablanca"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  carousel_slider: 5.1.1
  provider: 6.1.5+1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  local_auth: ^2.1.7
  crypto: ^3.0.3
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.3
  date_picker_timeline: ^1.2.6
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
